FROM node:20-alpine
WORKDIR /app

# Herramientas útiles para depuración en contenedor (curl)
RUN apk add --no-cache curl

COPY client/package*.json ./
RUN npm install

COPY client/. .

ENV NODE_ENV=development
EXPOSE 5173

CMD ["npm","run","dev","--","--host","0.0.0.0"]
